In [1]:
import pickle
import numpy as np

# c3d feature
y = np.load('crop_mean.npy')

print(y)

[[[[76.87925  81.45539  82.91122 ]
   [76.90526  81.45103  83.00473 ]
   [76.77082  81.259674 82.92529 ]
   ...
   [76.17821  80.61866  81.55207 ]
   [75.95166  80.38075  81.34317 ]
   [75.77195  80.13152  81.12227 ]]

  [[76.172646 80.92904  82.4708  ]
   [76.548096 81.284874 82.90656 ]
   [76.70415  81.40872  83.088234]
   ...
   [76.303215 80.808975 81.75366 ]
   [75.99177  80.490005 81.46176 ]
   [75.539406 79.9691   80.94476 ]]

  [[76.25879  81.11641  82.58669 ]
   [76.38894  81.19404  82.73525 ]
   [76.71191  81.50199  83.08748 ]
   ...
   [76.30527  80.858315 81.67607 ]
   [75.94894  80.4762   81.333435]
   [75.81948  80.27844  81.14025 ]]

  ...

  [[69.07567  74.61454  79.089195]
   [69.39426  74.92995  79.72587 ]
   [69.30291  74.87464  79.71863 ]
   ...
   [69.456085 75.402504 78.15093 ]
   [69.56299  75.47531  78.24672 ]
   [69.45152  75.363106 78.15694 ]]

  [[69.330795 74.786    79.0258  ]
   [69.47998  74.94823  79.456924]
   [69.45808  74.99825  79.62466 ]
   ...
   [6