In [52]:
import pickle
import numpy as np

#train_csv_path = "E:/File/Deep_Learning/model/TALL-master/exp_data/TACoS/train_clip-sentvec.pkl"
test_csv_path = "./exp_data/train_sentence.pkl"
#train_s = pickle.load(open(train_csv_path, 'rb'), encoding="latin1")
test_s = pickle.load(open(test_csv_path, 'rb'), encoding="latin1")

#train = [i[1] for i in train_s]
test = [k for k, v in test_s.items()]

#for i in train_s:
#    sent_name = i[0]
#    sent_vecs = i[1]
#    print(sent_name, len(sent_vecs))
#sent_name = train_s[7][0]
#print(sent_name)
#sent_vecs = train_s[7][1]
#for vec in sent_vecs:
#    print(vec)

#print(len(train))
#print(len(test))

#print(train_s[0])
#print(train_s[1])
print(test[1], test_s[test[1]][0])
print(test[2], test_s[test[2]][0])
print(test[3], test_s[test[3]][0])
"""
v = np.array(([1, 2, 3, 4], [5, 6, 7, 8]))
s = np.array(([1, 2, 3, 4], [5, 6, 7, 8]))
vv = np.reshape(np.tile(v, [2, 1]), [2, 2, 4])
ss = np.reshape(np.tile(s, [1, 2]), [2, 2, 4])

for i in range(vv.shape[0]):
    print(i)
    print(vv[i])
    print(ss[i])

#print(y)
"""
# c3d feature
#y = np.load('crop_mean.npy')

#print(y)

s13-d21_252_452 [[-0.02507035  0.01792968 -0.00489204 ...  0.06062402  0.02171551
   0.03321327]]
s13-d21_471_627 [[-0.0141677   0.01069785 -0.00177013 ...  0.03334549  0.00467701
   0.01666418]]
s13-d21_627_686 [[-0.02699237  0.01298359 -0.00726358 ...  0.03505049 -0.00138477
   0.00839384]]


'\nv = np.array(([1, 2, 3, 4], [5, 6, 7, 8]))\ns = np.array(([1, 2, 3, 4], [5, 6, 7, 8]))\nvv = np.reshape(np.tile(v, [2, 1]), [2, 2, 4])\nss = np.reshape(np.tile(s, [1, 2]), [2, 2, 4])\n\nfor i in range(vv.shape[0]):\n    print(i)\n    print(vv[i])\n    print(ss[i])\n\n#print(y)\n'

In [ ]:
import numpy as np
import ctrl_model

train_feature_dir = "E:/File/VS Code/DataSet/TACOS/Interval64_128_i3d_mixed5/"
test_feature_dir = "E:/File/VS Code/DataSet/TACoS/Interval128_i3d_mixed5/"
train_csv_path = "./exp_data/train_sentence.pkl"
test_csv_path = "./exp_data/test_sentence.pkl"
"""
train_feature_dir = "E:/File/VS Code/DataSet/TACOS/Interval64_128_256_512_overlap0.8_c3d_fc6/"
test_feature_dir = "E:/File/VS Code/DataSet/TACoS/Interval128_256_overlap0.8_c3d_fc6/"
train_csv_path = "./exp_data/TACoS/train_clip-sentvec.pkl"
test_csv_path = "./exp_data/TACoS/test_clip-sentvec.pkl"
"""
model = ctrl_model.CTRL_Model(train_feature_dir, train_csv_path, test_feature_dir, test_csv_path, 50)

#Reading testing data list from ./exp_data/TACoS/train_clip-sentvec.pkl
#10146 clip-sentence pairs are readed
#26963 iou clip-sentence pairs are readed
#Reading testing data list from ./exp_data/TACoS/test_clip-sentvec.pkl
#4083 pairs are readed
#Max number of clips in a movie is 242
#sliding clips number: 15881

In [7]:
import numpy as np
import os
import random
import time
import skip_thoughts.skipthoughts as skipthoughts

encoder = skipthoughts.Encoder(skipthoughts.load_model())
sent_feat = []
query_sent = ['the person set up for his kitchen activities', 'the person wiped the cucumber', 
                'the person wiped the cucumber', 'the person wiped the cucumber',
                'the person wiped the cucumber', 'the person wiped the cucumber',
                'the person wiped the cucumber', 'the person wiped the cucumber',
                'the person wiped the cucumber', 'the person wiped the cucumber']

start = time.time()
#for i in range(len(query_sent)):
query_vec = encoder.encode(query_sent)
print(time.time() - start)

start = time.time()
for i in range(len(query_sent)):
    query_vec = encoder.encode([query_sent[i]])
print(time.time() - start)

#for i in range(len(query_vec)):
#    print(query_vec[i])


Loading model parameters...
Compiling encoders...
Loading tables...
Packing up...
14.885078430175781
18.463918685913086


In [ ]:
import os
import numpy as np

train_dir = "E:/File/VS Code/DataSet/TACOS/Interval64_128_256_512_overlap0.8_c3d_fc6/"
test_dir = "E:/File/VS Code/DataSet/TACoS/Interval128_256_overlap0.8_c3d_fc6/"
train_feature_dir = "E:/File/VS Code/DataSet/TACOS/Interval64_128_i3d_mixed5/"
test_feature_dir = "E:/File/VS Code/DataSet/TACoS/Interval128_i3d_mixed5/"

clip_name = 's17-d69.avi_1_65.npy'
movie_clip_name = 's17-d69_0_64.npy'

feature = np.load(os.path.join(train_dir, clip_name))

print(feature)

In [17]:
import numpy as np

context_size = 1

left = np.array([[1, 2, 3, 4]]) # [1, 4]
data = np.array([0, 0, 0, 0]) # [4]
right = np.array([[4, 5, 6, 7]]) # [1, 4]

left = np.transpose(left, [1,0]) # [4, 2]
right = np.transpose(right, [1,0]) # [4, 2]

comb_feat = np.column_stack((left, data, right))
print(comb_feat.shape)

for i in comb_feat: print(i)

featmap = np.reshape(comb_feat, [1, comb_feat.shape[0] * (2 * context_size + 1)])
print(featmap.shape)

for i in featmap: print(i)

(4, 3)
[1 0 4]
[2 0 5]
[3 0 6]
[4 0 7]
(1, 12)
[1 0 4 2 0 5 3 0 6 4 0 7]


In [45]:
import tensorflow.compat.v1 as tf

with tf.Session() as sess:

    matricesList = tf.constant([[[[1, 2, 3], [4, 5, 6]], 
                                 [[7, 8, 9], [10, 11, 12]]]])
    print(matricesList.shape)
    #matricesSum = tf.reduce_min(matricesList, axis=2)
    #matricesSum = tf.reduce_min(matricesList, axis=2)
    matricesSum = tf.reduce_mean(matricesList, axis=[1,2])
    matricesSum = tf.expand_dims(matricesSum, 1)
    matricesSum = tf.expand_dims(matricesSum, 2)

    attention = tf.multiply(matricesList, matricesSum)
    print(matricesSum.shape)
    print(attention.shape)

    print(sess.run(attention))

(1, 2, 2, 3)
(1, 1, 1, 3)
(1, 2, 2, 3)
[[[[ 5 12 21]
   [20 30 42]]

  [[35 48 63]
   [50 66 84]]]]
